'use strict';
const $ = (s,root=document)=>root.querySelector(s);
const app=$('#app'),modal=$('#modal');
let user=null,state=null,page='Dashboard',mode='login',filters={q:'',type:'',status:'',warehouse:'',location:'',category:''},refreshing=false;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>Number(v).toLocaleString(undefined,{maximumFractionDigits:3});
const icons={Dashboard:'▦',Products:'◇',Receipts:'↙','Delivery Orders':'↗','Internal Transfers':'⇄','Inventory Adjustment':'≋','Move History':'◷',Settings:'⚙','My Profile':'○'};
const types={Receipts:'Receipt','Delivery Orders':'Delivery','Internal Transfers':'Internal','Inventory Adjustment':'Adjustment'};
const symbols={Receipt:'↙',Delivery:'↗',Internal:'⇄',Adjustment:'≋'};
const brand='<div class="brand"><span class="brandmark">⬡</span>Stock<span>Sense<small>.</small></span></div>';
const pby=id=>state.products.find(p=>p.id===Number(id));
const locationName=id=>{const l=state.locations.find(l=>l.id===Number(id));return l?`${l.warehouse} / ${l.name}`:'—';};
const badge=s=>`<span class="badge ${esc(s)}">${esc(s)}</span>`;
const reference=d=>`${{Receipt:'REC',Delivery:'DEL',Internal:'INT',Adjustment:'ADJ'}[d.type]}/${String(d.id).padStart(5,'0')}`;
function toast(message){const t=$('#toast');t.textContent=message;t.style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.style.display='none',4200);}
async function api(path,data){const res=await fetch('/api/'+path,{method:data===undefined?'GET':'POST',headers:data===undefined?{}:{'Content-Type':'application/json','X-StockSense':'1'},body:data===undefined?undefined:JSON.stringify(data)});const body=await res.json();if(!res.ok){if(res.status===401&&user){user=null;renderAuth();}throw new Error(body.error||'Request failed');}return body;}
function authField(label,name,type='text',extra=''){return `<label class="field">${label}<input name="${name}" type="${type}" required ${extra}></label>`;}
function renderAuth(message=''){
 const signup=mode==='signup',forgot=mode==='forgot',reset=mode==='reset';
 const title=signup?'Create your workspace account':forgot?'Forgot your password?':reset?'Set a new password':'Welcome back';
 app.innerHTML=`<div class="auth"><section class="auth-art">${brand}<div><div class="eyebrow">LESS GUESSWORK. MORE CONTROL.</div><h1>Every item.<br>Every move.<br>All in sync.</h1><p>A clear view of your inventory, from the first receipt to the final delivery.</p><div class="art-grid"><div class="art-box">↙<small>Receive</small></div><div class="art-box">⬡<small>Organize</small></div><div class="art-box">↗<small>Deliver</small></div></div><p>Built for the people who keep things moving.</p></section><section class="auth-main"><div class="auth-card"><div class="mobile-brand">${brand}</div><div class="eyebrow">YOUR INVENTORY, SIMPLIFIED</div><h1>${title}</h1><p class="subtitle">${signup?'Your first account becomes the inventory manager.':forgot?'We’ll email a six-digit code to reset your password.':reset?'Enter your code and choose a strong password.':'Sign in to see what’s moving today.'}</p><form id="auth-form">${message?`<p class="success">${esc(message)}</p>`:''}<div id="auth-error"></div>${signup?authField('Full name','name','text','autocomplete="name" maxlength="200"'):''}${authField('Email address','email','email','autocomplete="email" maxlength="200"')}${reset?authField('Six-digit code','code','text','inputmode="numeric" pattern="[0-9]{6}" autocomplete="one-time-code"'):''}${!forgot?authField('Password','password','password',`minlength="10" maxlength="256" autocomplete="${signup||reset?'new-password':'current-password'}"`):''}${!forgot?'<p class="hint">Use at least 10 characters.</p>':''}<button class="primary full" type="submit">${signup?'Create account':forgot?'Send reset code':reset?'Reset password':'Sign in'} →</button></form><div class="auth-links">${mode==='login'?'<button class="link" data-mode="signup">Create an account</button><button class="link" data-mode="forgot">Forgot password?</button>':'<button class="link" data-mode="login">Back to sign in</button>'}${forgot?'<button class="link" data-mode="reset">I have a code</button>':''}</div></div></section></div>`;
 document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;renderAuth();});
 $('#auth-form').onsubmit=async e=>{e.preventDefault();const b=$('button[type=submit]',e.target);b.disabled=true;try{const result=await api(mode,Object.fromEntries(new FormData(e.target)));if(forgot){mode='reset';renderAuth(result.message);}else if(reset){mode='login';renderAuth(result.message);}else{user=result;await refresh();}}catch(err){$('#auth-error').innerHTML=`<p class="error">${esc(err.message)}</p>`;}finally{b.disabled=false;}};
}
async function refresh(){state=await api('state');render();}
function navigate(target){page=target;filters={q:'',type:'',status:'',warehouse:'',location:'',category:''};render();}
function render(){
 app.innerHTML=`<div class="shell"><aside class="sidebar">${brand}<div class="workspace">◉ &nbsp; Inventory workspace</div><div class="nav-label">WORKSPACE</div><nav class="nav">${Object.entries(icons).map(([name,icon])=>`<button data-page="${name}" class="${page===name?'active':''}"><span class="icon">${icon}</span>${name}</button>`).join('')}</nav><div class="sidebar-bottom"><p class="hint">Everything in its right place.</p><button class="profile-button" data-page="My Profile"><span class="avatar">${esc(user.name.slice(0,1).toUpperCase())}</span><span>${esc(user.name)}<small>${esc(user.role==='manager'?'Inventory manager':'Warehouse staff')}</small></span></button></div></aside><main class="main"><header class="topbar"><span>Workspace &nbsp; / &nbsp; <strong>${page}</strong></span><span class="live"><span class="dot"></span><span id="sync-label">Synced · refreshes every 15s</span></span></header><div class="content" id="content"></div></main></div>`;
 document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>navigate(b.dataset.page));renderContent();
}
function heading(title,subtitle,action=''){return `<div class="heading"><div><div class="eyebrow">INVENTORY WORKSPACE</div><h1>${title}</h1><p class="subtitle">${subtitle}</p></div>${action}</div>`;}
function options(items,value='',label='All'){return `<option value="">${label}</option>`+items.map(([id,name])=>`<option value="${esc(id)}" ${String(value)===String(id)?'selected':''}>${esc(name)}</option>`).join('');}
function filterBar(includeTypes=true){return `<div class="filters"><input type="search" aria-label="Search by SKU, product or reference" data-filter="q" placeholder="Search SKU, product or reference…" value="${esc(filters.q)}">${includeTypes?`<select aria-label="Document type" data-filter="type">${options(['Receipt','Delivery','Internal','Adjustment'].map(x=>[x,x]),filters.type,'All operations')}</select><select aria-label="Status" data-filter="status">${options(['Draft','Waiting','Ready','Done','Canceled'].map(x=>[x,x]),filters.status,'All statuses')}</select>`:''}<select aria-label="Warehouse" data-filter="warehouse">${options(state.warehouses.map(w=>[w.id,w.name]),filters.warehouse,'All warehouses')}</select><select aria-label="Location" data-filter="location">${options(state.locations.filter(l=>!filters.warehouse||String(l.warehouse_id)===filters.warehouse).map(l=>[l.id,l.name]),filters.location,'All locations')}</select><select aria-label="Category" data-filter="category">${options([...new Set(state.products.map(p=>p.category))].map(c=>[c,c]),filters.category,'All categories')}</select></div>`;}
function matchesProduct(p){return (!filters.category||p.category===filters.category)&&(!filters.q||`${p.name} ${p.sku}`.toLowerCase().includes(filters.q.toLowerCase()));}
function matchesLocation(id){const loc=state.locations.find(l=>l.id===id);return (!filters.location||String(id)===filters.location)&&(!filters.warehouse||String(loc?.warehouse_id)===filters.warehouse);}
function filteredDocs(){return state.documents.filter(d=>{
 const lines=state.lines.filter(l=>l.document_id===d.id),q=filters.q.toLowerCase();
 return (!types[page]||d.type===types[page])&&(!filters.type||d.type===filters.type)&&(!filters.status||d.status===filters.status)&&(matchesLocation(d.source_id)||matchesLocation(d.destination_id))&&(!filters.category||lines.some(l=>pby(l.product_id)?.category===filters.category))&&(!q||`${reference(d)} ${d.partner}`.toLowerCase().includes(q)||lines.some(l=>{const p=pby(l.product_id);return `${p?.sku} ${p?.name}`.toLowerCase().includes(q);}));
 });}
function empty(title,text){return `<div class="empty"><strong>${title}</strong>${text}</div>`;}
function docTable(docs){return docs.length?`<div class="table-wrap"><table><thead><tr><th>REFERENCE</th><th>OPERATION</th><th>PARTNER / ROUTE</th><th>SCHEDULED</th><th>STATUS</th><th></th></tr></thead><tbody>${docs.map(d=>`<tr><td><strong>${reference(d)}</strong><small>${state.lines.filter(l=>l.document_id===d.id).length} product line(s)</small></td><td><span class="type"><span class="type-icon">${symbols[d.type]}</span>${d.type}</span></td><td>${esc(d.partner||locationName(d.source_id||d.destination_id))}${d.type==='Internal'?`<small>→ ${esc(locationName(d.destination_id))}</small>`:''}</td><td>${esc(d.scheduled)}</td><td>${badge(d.status)}</td><td><button class="link" data-document="${d.id}">View →</button></td></tr>`).join('')}</tbody></table></div>`:empty('No operations here yet','Create an operation or adjust your filters.');}
function dashboard(){
 const docs=filteredDocs(), products=state.products.filter(matchesProduct).map(p=>({...p,total:state.stock.filter(s=>s.product_id===p.id&&matchesLocation(s.location_id)).reduce((n,s)=>n+s.qty,0)}));
 const low=products.filter(p=>p.total<=p.reorder),pending=t=>docs.filter(d=>d.type===t&&!['Done','Canceled'].includes(d.status)).length;
 const cards=[['Products in stock',products.filter(p=>p.total>0).length,'Unique products available','◇'],['Low / out of stock',low.length,'At or below reorder level','!'],['Pending receipts',pending('Receipt'),'Incoming goods to process','↙'],['Pending deliveries',pending('Delivery'),'Orders awaiting dispatch','↗'],['Internal transfers',pending('Internal'),'Scheduled stock movements','⇄']];
 return heading('Inventory overview','A little clarity for everything you have in stock.','<button class="primary" id="new-operation">＋ New operation</button>')+`<div class="kpis">${cards.map(([name,n,note,icon],i)=>`<div class="kpi ${i===1?'warn':''}"><span class="kpi-symbol">${icon}</span><div class="kpi-label">${name}</div><div class="kpi-value">${num(n)}</div><div class="kpi-note">${note}</div></div>`).join('')}</div><section class="panel"><div class="panel-head"><div><h2>Operations overview</h2><p>Follow every movement, from draft to done.</p></div><span class="badge">${docs.length} operations</span></div>${filterBar()}${docTable(docs.slice(0,30))}</section><div class="split"><section class="panel"><div class="panel-head"><div><h2>Needs your attention</h2><p>Products that have reached their reorder point.</p></div><span class="badge Waiting">${low.length} items</span></div><div class="stock-list">${low.slice(0,5).map(p=>`<div class="stock-row"><span class="product-icon">◇</span><div class="stock-info">${esc(p.name)}<small>${esc(p.sku)} · ${esc(p.category)}</small></div><div class="stock-amount">${num(p.total)} ${esc(p.unit)}<small>Minimum ${num(p.reorder)} ${esc(p.unit)}</small></div></div>`).join('')||empty('All clear','No products below their reorder point.')}</div></section><section class="panel"><div class="panel-head"><div><h2>Your storage network</h2><p>Connected locations. One source of truth.</p></div><span class="type-icon">⬡</span></div><div class="stock-list">${state.warehouses.map(w=>`<div class="stock-row"><span class="product-icon">▥</span><div class="stock-info">${esc(w.name)}<small>${state.locations.filter(l=>l.warehouse_id===w.id).map(l=>esc(l.name)).join(' · ')}</small></div><span class="badge healthy">Active</span></div>`).join('')||empty('Set up your first warehouse','Open Settings to add a warehouse and storage location.')}</div></section></div><div class="footnote"><span>StockSense · Inventory, in sync.</span><span>Ledger records are retained for every validated movement.</span></div>`;
}
function productsView(){const products=state.products.filter(matchesProduct);return heading('Products','Your catalog, availability, and replenishment rules.',user.role==='manager'?'<button class="primary" id="new-product">＋ Add product</button>':'')+`<section class="panel">${filterBar(false)}${products.length?`<div class="table-wrap"><table><thead><tr><th>PRODUCT</th><th>CATEGORY</th><th>AVAILABLE</th><th>REORDER POINT</th><th>STOCK STATUS</th><th></th></tr></thead><tbody>${products.map(p=>{const qty=state.stock.filter(s=>s.product_id===p.id&&matchesLocation(s.location_id)).reduce((n,s)=>n+s.qty,0);return `<tr><td><strong>${esc(p.name)}</strong><small>${esc(p.sku)}</small></td><td>${esc(p.category)}</td><td>${num(qty)} ${esc(p.unit)}</td><td>${num(p.reorder)} ${esc(p.unit)}</td><td>${badge(qty<=p.reorder?'low':'healthy')}</td><td><button class="link" data-product="${p.id}">Details →</button></td></tr>`;}).join('')}</tbody></table></div>`:empty('Your catalog starts here','Add a product with a unique SKU to begin tracking stock.')}</section>`;}
function historyView(){const ledger=state.ledger.filter(l=>matchesLocation(l.location_id)&&matchesProduct(pby(l.product_id)));return heading('Move history','An immutable audit trail of validated inventory movements.')+`<section class="panel">${filterBar(false)}${ledger.length?`<div class="table-wrap"><table><thead><tr><th>WHEN / USER</th><th>REFERENCE</th><th>PRODUCT</th><th>LOCATION</th><th>CHANGE</th><th>BALANCE AFTER</th></tr></thead><tbody>${ledger.map(l=>`<tr><td>${esc(l.created_at)} UTC<small>${esc(l.actor)}</small></td><td>${reference(state.documents.find(d=>d.id===l.document_id))}</td><td><strong>${esc(pby(l.product_id).name)}</strong><small>${esc(pby(l.product_id).sku)}</small></td><td>${esc(locationName(l.location_id))}</td><td><strong>${l.delta>0?'+':''}${num(l.delta)} ${esc(pby(l.product_id).unit)}</strong></td><td>${num(l.balance)}</td></tr>`).join('')}</tbody></table></div>`:empty('No movements yet','Validate an operation to create your first ledger entry.')}</section><p class="hint">Showing the latest 1,000 ledger entries. All historical entries remain stored in the database.</p>`;}
function settingsView(){return heading('Warehouses & locations','Organize your storage network across warehouses, floors, and racks.',user.role==='manager'?'<button class="primary" id="new-warehouse">＋ Add warehouse / location</button>':'')+`<section class="panel">${state.warehouses.map(w=>`<div class="warehouse-card"><h2>▥ &nbsp;${esc(w.name)}</h2><p>${state.locations.filter(l=>l.warehouse_id===w.id).length} storage locations</p><div class="location-tags">${state.locations.filter(l=>l.warehouse_id===w.id).map(l=>`<span>${esc(l.name)}</span>`).join('')}</div></div>`).join('')||empty('Make room for your inventory','Add your first warehouse and location to start receiving goods.')}</section>`;}
function renderContent(){
 let html;if(page==='Dashboard')html=dashboard();else if(page==='Products')html=productsView();else if(page==='Move History')html=historyView();else if(page==='Settings')html=settingsView();else if(page==='My Profile')html=heading('My profile','Your account and workspace access.')+`<section class="panel"><div class="modal-body"><form id="profile-form">${authField('Name','name','text',`value="${esc(user.name)}" maxlength="200"`)}<p class="subtitle">${esc(user.email)} · ${esc(user.role)}</p><div class="modal-footer"><button type="button" id="logout">Log out</button><button class="primary">Save profile</button></div></form></div></section>`;else html=heading(page,{Receipt:'Receive vendor goods into a storage location.',Delivery:'Pick, pack, and dispatch stock with confidence.',Internal:'Move inventory between locations without changing your total.',Adjustment:'Reconcile recorded stock with a physical count.'}[types[page]],'<button class="primary" id="new-operation">＋ New operation</button>')+`<section class="panel">${filterBar()}${docTable(filteredDocs())}</section>`;
 $('#content').innerHTML=html;bindContent();
}
function bindContent(){
 document.querySelectorAll('[data-filter]').forEach(el=>el.oninput=()=>{const key=el.dataset.filter,position=el.selectionStart;filters[key]=el.value;if(key==='warehouse')filters.location='';renderContent();const next=$(`[data-filter="${key}"]`);next.focus();if(key==='q')next.setSelectionRange(position,position);});
 document.querySelectorAll('[data-document]').forEach(b=>b.onclick=()=>showDocument(Number(b.dataset.document)));
 document.querySelectorAll('[data-product]').forEach(b=>b.onclick=()=>productModal(pby(b.dataset.product)));
 if($('#new-operation'))$('#new-operation').onclick=()=>operationModal(types[page]||'Receipt');
 if($('#new-product'))$('#new-product').onclick=()=>productModal();
 if($('#new-warehouse'))$('#new-warehouse').onclick=warehouseModal;
 if($('#logout'))$('#logout').onclick=async()=>{try{await api('logout',{});user=null;mode='login';renderAuth();}catch(e){toast(e.message);}};
 if($('#profile-form'))$('#profile-form').onsubmit=async e=>{e.preventDefault();try{await api('profile',Object.fromEntries(new FormData(e.target)));user=await api('me');render();toast('Profile updated');}catch(err){toast(err.message);}};
}
function openModal(title,body){modal.innerHTML=`<div class="modal-head"><h2>${esc(title)}</h2><button id="close-modal" aria-label="Close dialog">✕</button></div><div class="modal-body">${body}</div>`;$('#close-modal').onclick=()=>modal.close();if(!modal.open)modal.showModal();}
function modalForm(title,body,onSubmit){openModal(title,`<form id="modal-form"><div id="modal-error"></div>${body}<div class="modal-footer"><button type="button" id="cancel-modal">Cancel</button><button class="primary" type="submit">Save</button></div></form>`);$('#cancel-modal').onclick=()=>modal.close();$('#modal-form').onsubmit=async e=>{e.preventDefault();const button=$('button[type=submit]',e.target);button.disabled=true;try{await onSubmit(Object.fromEntries(new FormData(e.target)),e.target);modal.close();await refresh();toast('Saved successfully');}catch(err){$('#modal-error').innerHTML=`<p class="error">${esc(err.message)}</p>`;}finally{button.disabled=false;}};}
function locSelect(name,label,value=''){return `<label class="field">${label}<select name="${name}" required>${options(state.locations.map(l=>[l.id,locationName(l.id)]),value,'Select location')}</select></label>`;}
function productModal(p){
 if(p&&user.role!=='manager'){openModal(p.name,stockLocations(p));return;}
 modalForm(p?'Edit product':'Add product',`<div class="form-grid">${authField('Product name','name','text',`value="${esc(p?.name||'')}" maxlength="200"`)}${authField('SKU / code','sku','text',`value="${esc(p?.sku||'')}" maxlength="200"`)}${authField('Category','category','text',`value="${esc(p?.category||'')}" list="categories" maxlength="200"`)}<datalist id="categories">${[...new Set(state.products.map(p=>p.category))].map(c=>`<option value="${esc(c)}">`).join('')}</datalist>${authField('Unit of measure','unit','text',`value="${esc(p?.unit||'units')}" maxlength="200"`)}${authField('Reorder point (per selected scope)','reorder','number',`min="0" max="1000000000000" step="0.001" value="${p?.reorder||0}"`)}${!p?authField('Initial stock (optional)','initial','number','min="0" max="1000000000000" step="0.001" value="0"')+`<label class="field wide">Initial stock location<select name="location_id">${options(state.locations.map(l=>[l.id,locationName(l.id)]),'','Select location if stock > 0')}</select></label>`:''}</div>${p?stockLocations(p):'<p class="hint">Opening stock creates a receipt and a ledger entry automatically.</p>'}`,async data=>api('products',{...data,...(p?{id:p.id}:{})}));
}
function stockLocations(p){return `<h2>Availability by location</h2><div class="stock-list">${state.stock.filter(s=>s.product_id===p.id).map(s=>`<div class="stock-row"><div class="stock-info">${esc(locationName(s.location_id))}</div><span>${num(s.qty)} ${esc(p.unit)}</span></div>`).join('')||'<p class="hint">No stock recorded yet.</p>'}</div>`;}
function warehouseModal(){modalForm('Add warehouse or storage location',`<label class="field">Warehouse<select name="warehouse_id" id="warehouse-choice">${options(state.warehouses.map(w=>[w.id,w.name]),'','Create a new warehouse')}</select></label>${authField('New warehouse name','name','text','maxlength="200"')}${authField('Location / rack name','location','text','maxlength="200"')}`,data=>api('warehouses',data));$('#warehouse-choice').onchange=e=>{const field=$('input[name=name]');field.required=!e.target.value;field.closest('label').hidden=!!e.target.value;};}
function operationModal(kind){
 if(!state.products.length||!state.locations.length){toast('Add a warehouse location and a product first.');return;}
 modalForm('New inventory operation',`<div class="form-grid"><label class="field">Operation type<select name="type" id="operation-type">${['Receipt','Delivery','Internal','Adjustment'].map(t=>`<option ${t===kind?'selected':''}>${t}</option>`).join('')}</select></label>${authField('Scheduled date','scheduled','date',`value="${new Date().toLocaleDateString('en-CA')}"`)}<div id="source-field">${locSelect('source_id','Source / counted location')}</div><div id="destination-field">${locSelect('destination_id','Destination location')}</div><label class="field wide">Supplier / customer (optional)<input name="partner" maxlength="200" placeholder="Company or contact name"></label></div><h2 id="line-heading">Products & quantities</h2><p class="hint" id="quantity-hint"></p><div id="lines"></div><button type="button" id="add-line">＋ Add product line</button><label class="field">Notes<textarea name="notes" maxlength="2000" rows="2"></textarea></label>`,async(data,form)=>{const lines=[...form.querySelectorAll('.line')].map(row=>({product_id:Number($('select',row).value),qty:$('input',row).value}));return api('documents',{...data,lines});});
 const update=()=>{const type=$('#operation-type').value;for(const [id,visible]of [['source-field',type!=='Receipt'],['destination-field',['Receipt','Internal'].includes(type)]]){const el=$('#'+id);el.hidden=!visible;$('select',el).disabled=!visible;}$('#quantity-hint').textContent=type==='Adjustment'?'Enter the physical counted quantity, not the difference. Zero is allowed.':'Enter the quantity to move, using each product’s unit of measure.';document.querySelectorAll('.line input').forEach(i=>i.min=type==='Adjustment'?'0':'0.001');};
 const addLine=()=>{const row=document.createElement('div');row.className='line';row.innerHTML=`<select aria-label="Product" required>${options(state.products.map(p=>[p.id,`${p.sku} · ${p.name} (${p.unit})`]),'','Choose product')}</select><input aria-label="Quantity" type="number" step="0.001" max="1000000000000" value="1" required><button type="button" aria-label="Remove line">×</button>`;$('button',row).onclick=()=>row.remove();$('#lines').append(row);update();};$('#add-line').onclick=addLine;$('#operation-type').onchange=update;addLine();
}
function showDocument(id){const d=state.documents.find(d=>d.id===id),lines=state.lines.filter(l=>l.document_id===id);let actions=[];if(d.status==='Draft')actions=[['wait','Confirm → Waiting']];if(d.status==='Waiting')actions=[['ready','Mark ready']];if(d.status==='Ready')actions=d.type==='Delivery'&&!d.picked?[['pick','Confirm picked']]:d.type==='Delivery'&&!d.packed?[['pack','Confirm packed']]:[['validate','Validate stock movement']];if(!['Done','Canceled'].includes(d.status))actions.push(['cancel','Cancel operation']);openModal(reference(d),`<dl class="detail"><div><dt>TYPE / STATUS</dt><dd>${d.type} · ${badge(d.status)}</dd></div><div><dt>SCHEDULED</dt><dd>${esc(d.scheduled)}</dd></div><div><dt>FROM</dt><dd>${esc(locationName(d.source_id))}</dd></div><div><dt>TO</dt><dd>${esc(locationName(d.destination_id))}</dd></div><div><dt>PARTNER</dt><dd>${esc(d.partner||'—')}</dd></div><div><dt>CREATED BY</dt><dd>${esc(d.creator)}</dd></div></dl><div class="stock-list">${lines.map(l=>`<div class="stock-row"><div class="stock-info">${esc(pby(l.product_id).name)}<small>${esc(pby(l.product_id).sku)}</small></div><span>${num(l.qty)} ${esc(pby(l.product_id).unit)}</span></div>`).join('')}</div>${d.type==='Delivery'?`<p class="hint">Picked: ${d.picked?'Yes':'No'} · Packed: ${d.packed?'Yes':'No'}</p>`:''}${d.type==='Adjustment'?'<p class="hint">Quantities represent physical counts. Validation records the difference against current stock.</p>':''}<p class="hint">${esc(d.notes)}</p><div id="action-error"></div><div class="modal-footer actions">${actions.map(([a,label])=>`<button data-action="${a}" class="${a==='cancel'?'':'primary'}">${label}</button>`).join('')}</div>`);document.querySelectorAll('[data-action]').forEach(b=>b.onclick=async()=>{document.querySelectorAll('[data-action]').forEach(x=>x.disabled=true);try{await api('transition',{id,action:b.dataset.action});await refresh();showDocument(id);toast('Operation updated');}catch(err){$('#action-error').innerHTML=`<p class="error">${esc(err.message)}</p>`;document.querySelectorAll('[data-action]').forEach(x=>x.disabled=false);}});}
async function start(){try{user=await api('me');await refresh();}catch{renderAuth();}}
setInterval(async()=>{if(!user||modal.open||document.hidden||refreshing||document.activeElement?.matches('input,select,textarea'))return;refreshing=true;try{state=await api('state');if(page!=='My Profile')renderContent();if($('#sync-label'))$('#sync-label').textContent='Synced · refreshes every 15s';}catch{if($('#sync-label'))$('#sync-label').textContent='Connection interrupted · retrying';}finally{refreshing=false;}},15000);
start();
